// <auto-generated />
using System;
using EnglishStudio.Modules.Reading.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnglishStudio.Modules.Reading.Data.Migrations
{
    [DbContext(typeof(ReadingDbContext))]
    [Migration("20260603065839_ReadingInitial")]
    partial class ReadingInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("EnglishStudio.Modules.Reading.Entities.ReadingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AccuracyPct")
                        .HasColumnType("REAL");

                    b.Property<string>("AudioPath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationSec")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReadingTextId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WordsRead")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Wpm")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ReadingTextId");

                    b.HasIndex("StartedAt");

                    b.ToTable("ReadingSessions");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Reading.Entities.ReadingText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedCefr")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastOpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("WordCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Source");

                    b.ToTable("ReadingTexts");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Reading.Entities.ReadingWordStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Mispronounced")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReadingSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Score")
                        .HasColumnType("REAL");

                    b.Property<bool>("Skipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TokenIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReadingSessionId");

                    b.ToTable("ReadingWordStats");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Reading.Entities.ReadingSession", b =>
                {
                    b.HasOne("EnglishStudio.Modules.Reading.Entities.ReadingText", "ReadingText")
                        .WithMany("Sessions")
                        .HasForeignKey("ReadingTextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReadingText");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Reading.Entities.ReadingWordStat", b =>
                {
                    b.HasOne("EnglishStudio.Modules.Reading.Entities.ReadingSession", "ReadingSession")
                        .WithMany("WordStats")
                        .HasForeignKey("ReadingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReadingSession");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Reading.Entities.ReadingSession", b =>
                {
                    b.Navigation("WordStats");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Reading.Entities.ReadingText", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
