// <auto-generated />
using System;
using EnglishStudio.Modules.Ielts.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnglishStudio.Modules.Ielts.Core.Data.Migrations
{
    [DbContext(typeof(IeltsDbContext))]
    [Migration("20260524082700_AddWritingSchema")]
    partial class AddWritingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("EnglishStudio.Modules.Ielts.Core.Entities.TestAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestAttemptId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestQuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAnswerJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TestAttemptId");

                    b.HasIndex("TestQuestionId");

                    b.ToTable("TestAnswers");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Ielts.Core.Entities.TestAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BandEstimate")
                        .HasColumnType("REAL");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTrainingMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RawScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TestSetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("TestSetId");

                    b.ToTable("TestAttempts");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Ielts.Core.Entities.TestPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioPath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyText")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("IntroNoteRu")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderInTest")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestSetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TestSetId");

                    b.HasIndex("TestSetId", "OrderInTest")
                        .IsUnique();

                    b.ToTable("TestParts");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Ielts.Core.Entities.TestQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcceptableAnswersJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnswerKeyJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderInPart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stem")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("TestPartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WordLimitMax")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TestPartId");

                    b.HasIndex("TestPartId", "OrderInPart")
                        .IsUnique();

                    b.ToTable("TestQuestions");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Ielts.Core.Entities.TestQuestionGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExampleAnswer")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExampleStem")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstructionText")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Layout")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderInPart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SharedListTitle")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SharedOptionsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryTemplate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TestPartId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TestPartId");

                    b.HasIndex("TestPartId", "OrderInPart")
                        .IsUnique();

                    b.ToTable("TestQuestionGroups");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Ielts.Core.Entities.TestSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorAttribution")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Section")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Section");

                    b.ToTable("TestSets");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Ielts.Core.Entities.WritingAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BandCoherence")
                        .HasColumnType("REAL");

                    b.Property<double?>("BandGrammar")
                        .HasColumnType("REAL");

                    b.Property<double?>("BandLexical")
                        .HasColumnType("REAL");

                    b.Property<double?>("BandOverall")
                        .HasColumnType("REAL");

                    b.Property<double?>("BandTaskAchievement")
                        .HasColumnType("REAL");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeedbackJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WordCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WritingTaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("WritingTaskId");

                    b.ToTable("WritingAttempts");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Ielts.Core.Entities.WritingModelAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnnotationJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BandLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WritingTaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WritingTaskId");

                    b.HasIndex("WritingTaskId", "BandLevel")
                        .IsUnique();

                    b.ToTable("WritingModelAnswers");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Ielts.Core.Entities.WritingTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChartSpecJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChartType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinWords")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecommendedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopicCategory")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Kind");

                    b.ToTable("WritingTasks");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Ielts.Core.Entities.TestAnswer", b =>
                {
                    b.HasOne("EnglishStudio.Modules.Ielts.Core.Entities.TestAttempt", "TestAttempt")
                        .WithMany("Answers")
                        .HasForeignKey("TestAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishStudio.Modules.Ielts.Core.Entities.TestQuestion", "TestQuestion")
                        .WithMany()
                        .HasForeignKey("TestQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TestAttempt");

                    b.Navigation("TestQuestion");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Ielts.Core.Entities.TestAttempt", b =>
                {
                    b.HasOne("EnglishStudio.Modules.Ielts.Core.Entities.TestSet", "TestSet")
                        .WithMany()
                        .HasForeignKey("TestSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TestSet");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Ielts.Core.Entities.TestPart", b =>
                {
                    b.HasOne("EnglishStudio.Modules.Ielts.Core.Entities.TestSet", "TestSet")
                        .WithMany("Parts")
                        .HasForeignKey("TestSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestSet");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Ielts.Core.Entities.TestQuestion", b =>
                {
                    b.HasOne("EnglishStudio.Modules.Ielts.Core.Entities.TestQuestionGroup", "Group")
                        .WithMany("Questions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EnglishStudio.Modules.Ielts.Core.Entities.TestPart", "TestPart")
                        .WithMany("Questions")
                        .HasForeignKey("TestPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("TestPart");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Ielts.Core.Entities.TestQuestionGroup", b =>
                {
                    b.HasOne("EnglishStudio.Modules.Ielts.Core.Entities.TestPart", "TestPart")
                        .WithMany("Groups")
                        .HasForeignKey("TestPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestPart");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Ielts.Core.Entities.WritingAttempt", b =>
                {
                    b.HasOne("EnglishStudio.Modules.Ielts.Core.Entities.WritingTask", "WritingTask")
                        .WithMany()
                        .HasForeignKey("WritingTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WritingTask");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Ielts.Core.Entities.WritingModelAnswer", b =>
                {
                    b.HasOne("EnglishStudio.Modules.Ielts.Core.Entities.WritingTask", "WritingTask")
                        .WithMany("ModelAnswers")
                        .HasForeignKey("WritingTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WritingTask");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Ielts.Core.Entities.TestAttempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Ielts.Core.Entities.TestPart", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Ielts.Core.Entities.TestQuestionGroup", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Ielts.Core.Entities.TestSet", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Ielts.Core.Entities.WritingTask", b =>
                {
                    b.Navigation("ModelAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
