// <auto-generated />
using System;
using EnglishStudio.Modules.Dictionary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnglishStudio.Modules.Dictionary.Data.Migrations
{
    [DbContext(typeof(DictionaryDbContext))]
    partial class DictionaryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.Collocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionEn")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExampleEn")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FrequencyRank")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeadWordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Headword")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedText")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Pattern")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationRu")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeadWordId");

                    b.HasIndex("Headword");

                    b.HasIndex("LinkedText");

                    b.HasIndex("Pattern");

                    b.HasIndex("LinkedText", "Pattern")
                        .IsUnique();

                    b.ToTable("Collocations");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.Example", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PhrasalVerbId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SenseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TextEn")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TextRu")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("WordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhrasalVerbId");

                    b.HasIndex("SenseId");

                    b.HasIndex("WordId");

                    b.ToTable("Examples");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.MediaAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attribution")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SenseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("WordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SenseId");

                    b.HasIndex("WordId");

                    b.ToTable("MediaAssets");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.PartOfSpeech", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PartsOfSpeech");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.PhrasalVerb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaseWordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CefrLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FrequencyRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Headword")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lemma")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Particle")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseWordId");

                    b.HasIndex("CefrLevel");

                    b.HasIndex("Headword");

                    b.HasIndex("Lemma");

                    b.HasIndex("Source");

                    b.HasIndex("BaseWordId", "Particle")
                        .IsUnique();

                    b.ToTable("PhrasalVerbs");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.PronunciationAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecognizedText")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetText")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("WordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("WordId");

                    b.ToTable("PronunciationAttempts");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.ReviewLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DifficultyAfter")
                        .HasColumnType("REAL");

                    b.Property<double>("DifficultyBefore")
                        .HasColumnType("REAL");

                    b.Property<double>("ElapsedDays")
                        .HasColumnType("REAL");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ScheduledIntervalDays")
                        .HasColumnType("REAL");

                    b.Property<double>("StabilityAfter")
                        .HasColumnType("REAL");

                    b.Property<double>("StabilityBefore")
                        .HasColumnType("REAL");

                    b.Property<int>("StateAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StateBefore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserWordProgressId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedAt");

                    b.HasIndex("UserWordProgressId");

                    b.ToTable("ReviewLogs");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.Sense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefinitionEn")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionRu")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PhrasalVerbId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhrasalVerbId");

                    b.HasIndex("WordId");

                    b.ToTable("Senses");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SenseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextRu")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SenseId");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.UserWordProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CollocationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Difficulty")
                        .HasColumnType("REAL");

                    b.Property<int>("LapseCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextReviewAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhrasalVerbId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Stability")
                        .HasColumnType("REAL");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CollocationId")
                        .IsUnique()
                        .HasFilter("\"CollocationId\" IS NOT NULL");

                    b.HasIndex("NextReviewAt");

                    b.HasIndex("PhrasalVerbId")
                        .IsUnique()
                        .HasFilter("\"PhrasalVerbId\" IS NOT NULL");

                    b.HasIndex("State");

                    b.HasIndex("WordId")
                        .IsUnique()
                        .HasFilter("\"WordId\" IS NOT NULL");

                    b.ToTable("UserWordProgress");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioUkPath")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioUsPath")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("CefrLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FrequencyRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Headword")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpaUk")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpaUs")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lemma")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("PartOfSpeechId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CefrLevel");

                    b.HasIndex("FrequencyRank");

                    b.HasIndex("Headword");

                    b.HasIndex("Lemma");

                    b.HasIndex("PartOfSpeechId");

                    b.HasIndex("Source");

                    b.HasIndex("Headword", "PartOfSpeechId")
                        .IsUnique();

                    b.ToTable("Words");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.WordCategory", b =>
                {
                    b.Property<int>("WordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WordId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("WordCategories");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.WordForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIrregular")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Form");

                    b.HasIndex("WordId");

                    b.ToTable("WordForms");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.WordTag", b =>
                {
                    b.Property<int>("WordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WordId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("WordTags");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.Category", b =>
                {
                    b.HasOne("EnglishStudio.Modules.Dictionary.Entities.Category", "ParentCategory")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.Collocation", b =>
                {
                    b.HasOne("EnglishStudio.Modules.Dictionary.Entities.Word", "HeadWord")
                        .WithMany()
                        .HasForeignKey("HeadWordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HeadWord");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.Example", b =>
                {
                    b.HasOne("EnglishStudio.Modules.Dictionary.Entities.PhrasalVerb", "PhrasalVerb")
                        .WithMany("Examples")
                        .HasForeignKey("PhrasalVerbId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EnglishStudio.Modules.Dictionary.Entities.Sense", "Sense")
                        .WithMany("Examples")
                        .HasForeignKey("SenseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EnglishStudio.Modules.Dictionary.Entities.Word", "Word")
                        .WithMany("Examples")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("PhrasalVerb");

                    b.Navigation("Sense");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.MediaAsset", b =>
                {
                    b.HasOne("EnglishStudio.Modules.Dictionary.Entities.Sense", "Sense")
                        .WithMany("Media")
                        .HasForeignKey("SenseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EnglishStudio.Modules.Dictionary.Entities.Word", "Word")
                        .WithMany("Media")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Sense");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.PhrasalVerb", b =>
                {
                    b.HasOne("EnglishStudio.Modules.Dictionary.Entities.Word", "BaseWord")
                        .WithMany()
                        .HasForeignKey("BaseWordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BaseWord");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.PronunciationAttempt", b =>
                {
                    b.HasOne("EnglishStudio.Modules.Dictionary.Entities.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.ReviewLog", b =>
                {
                    b.HasOne("EnglishStudio.Modules.Dictionary.Entities.UserWordProgress", "UserWordProgress")
                        .WithMany("ReviewLogs")
                        .HasForeignKey("UserWordProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserWordProgress");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.Sense", b =>
                {
                    b.HasOne("EnglishStudio.Modules.Dictionary.Entities.PhrasalVerb", "PhrasalVerb")
                        .WithMany("Senses")
                        .HasForeignKey("PhrasalVerbId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EnglishStudio.Modules.Dictionary.Entities.Word", "Word")
                        .WithMany("Senses")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("PhrasalVerb");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.Translation", b =>
                {
                    b.HasOne("EnglishStudio.Modules.Dictionary.Entities.Sense", "Sense")
                        .WithMany("Translations")
                        .HasForeignKey("SenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sense");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.UserWordProgress", b =>
                {
                    b.HasOne("EnglishStudio.Modules.Dictionary.Entities.Collocation", "Collocation")
                        .WithMany()
                        .HasForeignKey("CollocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EnglishStudio.Modules.Dictionary.Entities.PhrasalVerb", "PhrasalVerb")
                        .WithMany()
                        .HasForeignKey("PhrasalVerbId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EnglishStudio.Modules.Dictionary.Entities.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Collocation");

                    b.Navigation("PhrasalVerb");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.Word", b =>
                {
                    b.HasOne("EnglishStudio.Modules.Dictionary.Entities.PartOfSpeech", "PartOfSpeech")
                        .WithMany("Words")
                        .HasForeignKey("PartOfSpeechId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PartOfSpeech");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.WordCategory", b =>
                {
                    b.HasOne("EnglishStudio.Modules.Dictionary.Entities.Category", "Category")
                        .WithMany("WordCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishStudio.Modules.Dictionary.Entities.Word", "Word")
                        .WithMany("WordCategories")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.WordForm", b =>
                {
                    b.HasOne("EnglishStudio.Modules.Dictionary.Entities.Word", "Word")
                        .WithMany("Forms")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.WordTag", b =>
                {
                    b.HasOne("EnglishStudio.Modules.Dictionary.Entities.Tag", "Tag")
                        .WithMany("WordTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishStudio.Modules.Dictionary.Entities.Word", "Word")
                        .WithMany("WordTags")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("WordCategories");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.PartOfSpeech", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.PhrasalVerb", b =>
                {
                    b.Navigation("Examples");

                    b.Navigation("Senses");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.Sense", b =>
                {
                    b.Navigation("Examples");

                    b.Navigation("Media");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.Tag", b =>
                {
                    b.Navigation("WordTags");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.UserWordProgress", b =>
                {
                    b.Navigation("ReviewLogs");
                });

            modelBuilder.Entity("EnglishStudio.Modules.Dictionary.Entities.Word", b =>
                {
                    b.Navigation("Examples");

                    b.Navigation("Forms");

                    b.Navigation("Media");

                    b.Navigation("Senses");

                    b.Navigation("WordCategories");

                    b.Navigation("WordTags");
                });
#pragma warning restore 612, 618
        }
    }
}
